[package]
name = "sticker2-web"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
edition = "2018"

[dependencies]
alpino-tokenizer = "0.2"
anyhow = "1"
clap = "2"
conllu = "0.5"
futures = "0.3"
serde_yaml = "0.8"
sticker2 = { version = "0.4", default-features = false }
tch = "= 0.2.0"
tide = "0.13.0"
async-std = { version = "1.6.0", features = ["attributes"] }